---
title: "ER01 - Analysis of velo'v usage data"
author: "Grégoire Beaudoire, Fabrice Lécuyer, Etienne Desbois"
date: "1 décembre 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading our data and time variables:

```{r}
library(ggplot2)
velov = read.csv("data.csv")
data = strptime(velov$Time, "%Y-%m-%dT%H:%M:%S")
velov$Day = substr(data, 9,11)
velov$Hour = strftime(data, '%H')
velov$Minutes = strftime(data, '%M')
velov$Hour = as.numeric(velov$Hour)
velov$Minutes = as.numeric(velov$Minutes)
velov$Time2 <- velov$Hour + velov$Minutes/60
```

### Overivew of velo'v data:

We have one week of data for every velo'v station in Lyon, taken from the grand Lyon website.

```{r}
head(velov)
```

### Analysis of the evolution of the available bikes on the station next to the ENS

```{r}
library(scales)
ecole=subset(velov,Station=="velov-7046")
ggplot(ecole,aes(x=Time2,y=Bikes,color=Day)) + geom_line()
```

```{r}
ggplot(ecole,aes(x=Hour,y=Bikes,color=Day,group=1)) + geom_smooth()
```

### Global analysis

Let's plot the number of available bikes in all stations relative to the time, on a week day:


```{r}
tuesdays = subset(velov,Day="29")
ggplot(tuesdays,aes(x=Time2,y=Bikes)) + geom_smooth()
```
